language: php
php:
  # - 5.6 -> phpunit/phpunit 6.1.x-dev requires php ^7.0
  - 7.0
  - 7.1

before_script:
  # Adding 'travis_retry' to the composer install command means it will run it 3 times so github connection failures no longer cause tests to fail.
  - travis_retry composer clearcache
  - travis_retry composer selfupdate
  - travis_retry composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --bootstrap src/PHPUnitTutorial/User.php tests/unit/PHPUnitTutorial/UserTest --coverage-text --testdox
